/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import {
  Center,
  Plane,
  Stage,
  useGLTF,
  useTexture,
} from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export default function Frame(props) {
  const group = useRef();
  const gltf = useGLTF("/frame.glb");
  // console.log(nodes);

  // const texture = useTexture("/painting.jpg");
  // console.log(materials);

  return (
    // <Stage
    //   contactShadow
    //   shadows
    //   adjustCamera
    //   intensity={0}
    //   contactShadowBlur={4}
    //   castShadow={true}
    //   receiveShadow
    //   environment="city"
    //   preset="rembrandt">
    // <group ref={group} {...props} dispose={null}>
    <primitive
      // position={[10, 0, 0]}
      object={gltf.scene}
      rotation={[-90, 0, 0]}
    />
    // </group>
    // </Stage>
  );
}

useGLTF.preload("/frame.glb");
